FROM docker.io/library/golang:1.26-bookworm
WORKDIR /src
ENV PATH="/usr/local/go/bin:${PATH}"
COPY servemedia/ /src/servemedia/
WORKDIR /src/servemedia
RUN go mod tidy && go test ./...
CMD ["go", "test", "./..."]
